### ISSUE TITLE
Xcode hangs on "Compiling Swift source files"  When I try to archive the target.

### ISSUE THREAD

**Issue by fanthus** [Pluto-Y/SwiftyEcharts#4]
尝试打包的时候卡在 「Compiling Swift source files」这步不动了（真机运行什么的没问题，只是 Archive 不行）。
不知道别人有没有遇到。
环境：Xcode8.3 & macOS 10.12.4

**Comment by Pluto-Y** [comment]
正在找原因中...

**Comment by Pluto-Y** [comment]
通过将之前的 `struct` 类型修改成 `class` 类型即可， 之前在设计的时候没有考虑清楚

**Comment by averyhome** [comment]
我也遇到了类似的问题 为什么 struct 改成 class 就能够archive了呢  还请大佬赐教
