### ISSUE TITLE
为什么没支持CocoaPods呢?

### ISSUE THREAD

**Issue by Joan-m** [Pluto-Y/SwiftyEcharts#5]
很喜欢这个库,但是我需要折线图里面的<动态数据+时间坐标轴>这个模块,可不可以安排先支持呢,非常感谢.
还有怎么没支持CocoaPods呢?

**Comment by Pluto-Y** [comment]
感谢，但是我不理解你说的动态数据+时间坐标轴，有官网的demo地址吗。
关于Cocoapods还在思考，因为现在怎么比较好的分模块，可以叫我QQ聊一下你想要的东西，84690217

**Comment by Joan-m** [comment]
xAxis: {
        type: 'time',
    },
<动态数据+时间坐标轴>我想要这个http://echarts.baidu.com/demo.html#dynamic-data2
你的demo里面备注的暂缺.

**Comment by Pluto-Y** [comment]
哦，看了一下，这个可以做，之前是缺少一些原生的封装，所以就搁置了，我这两天做出一个demo你看看
